### ISSUE TITLE
Fleece Python

### ISSUE THREAD

**Issue by christianwensel** [couchbaselabs/fleece#110]
I would love to implement Fleece in pure python to make it more useable in serverless and other misc applications. (Or insert other serverless language JS for example). The CLI is useful for sure but limited. Love the performance and append-ability. My C is not my strong suit. Are there any design docs or anything available are about the fleece format. Else I’ll have to go down memory lane and read the C code. Gonna take a stab at it. Thanks team love your work.

**Comment by borrrden** [comment]
I'd appreciate it if you could ask question on the [forums](https://forums.couchbase.com/c/mobile/14) so that we can leave the issues page for bug reports.  Thanks!
