### ISSUE TITLE
BSL Question 

### ISSUE THREAD

**Issue by frank-dspeed** [couchbaselabs/fleece#134]
I am now not really sure if i can integrate that data structure anywhere as i am not sure if any Commercial product can use it for free. How can i be sure that i can implement this for example in my Own Coding Lang that i offer under Apache 2 license.

and then some one creates a Commercial Product with that and maybe even hosts that. 

How much licenses of which product would he need to buy to deploy a Application that uses fleece as Storage Structure and maybe even for sending the data to a Private Sold Android app.

**Comment by borrrden** [comment]
Please ask questions like this either on [the forums](https://forums.couchbase.com/c/mobile/14) or by using the [official contact form](https://www.couchbase.com/contact) so that the issue tracker can be left for issues with the product.
