### ISSUE TITLE
Xcode compile error in Backtrace.cc, after #140 merged

### ISSUE THREAD

**Issue by snej** [couchbaselabs/fleece#142]
PR #140 introduces an implicit conversion from `size_t` to `unsigned`, which causes the Xcode build to break (for macOS, probably also iOS):

```
fleece/Fleece/Support/Backtrace.cc:141:35: error: implicit conversion loses integer precision: 'decltype(this->_addrs.size())' (aka 'unsigned long') to 'unsigned int' [-Werror,-Wshorten-64-to-32]
            auto frame = getFrame(i);
                         ~~~~~~~~ ^
```

~~I don't know why this wasn't caught by CI; the macOS build there passed.~~ It passed CI because CMake doesn't enable `-Wshorten-64-to-32` Just ran a CMake build on my Mac on the same commit and it passed. 

I distinctly remember setting up an `xcodebuild` task in Github Actions, which would have caught this; hmm.

**Comment by borrrden** [comment]
The xcodebuild action you set up was in the litecore repo, not this one.  The reason it didn't get hit was because I forgot to get a review and merge on this change before doing the LiteCore side so the Fleece submodule is still lagging behind pre-change.
