### ISSUE TITLE
compilation on Windows with msvc fails

### ISSUE THREAD

**Issue by KraemerDEM** [couchbaselabs/fleece#30]
Currently fleece can not be compiled using MSVC, due to the following errors:
- MSVC doesn't seem to support zero sized arrays in structs so the definition of
 struct offsetValue in HeapValue.hh, line 17 leads to 
"error C2503: 'fleece::internal::offsetValue': base classes cannot contain zero-sized arrays"
- the definition of kInlineCapacity in ValueSlot.hh, Line 70 doesn't properly detect _inlineData and _moreInlineData:
"error C2327: 'fleece::internal::ValueSlot::_inlineData': is not a type name, static, or enumerator"
This can be fixed by adding "ValueSlot::":
 static constexpr size_t kInlineCapacity = sizeof(ValueSlot::_inlineData) + sizeof(ValueSlot::_moreInlineData);
- MSVC doesn't allow variable sized arrays, so it fails in Delta.cc line 129:
"error C2131: expression did not evaluate to a constant"
Maybe use _alloca or _malloca instead?

**Comment by borrrden** [comment]
This is being worked on in PR #31

**Comment by borrrden** [comment]
P.S. The next release is on the release/CBL2.1.x branch, not master FYI (in case you are wondering)
