### ISSUE TITLE
Windows build error: missing gmtime_r and localtime_r

### ISSUE THREAD

**Issue by snej** [couchbaselabs/fleece#37]
Windows builds are failing since I added ParseDate.cc, due to missing `gmtime_r` and `localtime_r` functions:

```
C:\projects\fleece\Fleece\Support\ParseDate.cc(369): error C2065: 'gmtime_r': undeclared identifier [C:\projects\fleece\build_cmake\x86\FleeceStatic.vcxproj]
C:\projects\fleece\Fleece\Support\ParseDate.cc(369): error C2065: 'localtime_r': undeclared identifier [C:\projects\fleece\build_cmake\x86\FleeceStatic.vcxproj]
```

The basic `gmtime` and `localtime` functions are in the C90 standard, but the `_r` variants are necessary for thread-safety; those are in the POSIX standard.

**Comment by borrrden** [comment]
Forgot to tag this but took care of both of these with 3bbf69d6c2aa4f9ce5af339cfeabc11359013d95 and a commit on LiteCore
